export const ActionTypes = {
  // CARD ACTIONS
  FETCH_CARDS_REQUEST: 'FETCH_CARDS_REQUEST',
  FETCH_CARDS_SUCCESS: 'FETCH_CARDS_SUCCESS',
  FETCH_CARDS_FAILURE: 'FETCH_CARDS_FAILURE',

  CREATE_CARD: 'CREATE_CARD',
  UPDATE_CARD: 'UPDATE_CARDS',
  REMOVE_CARD: 'REMOVE_CARD',

  SET_SELECTED_CARDS: 'SET_SELECTED_CARDS',
  REMOVE_SELECTED_CARDS: 'REMOVE_SELECTED_CARDS',

  // BUCKET ACTIONS
  FETCH_BUCKETS: 'FETCH_BUCKETS',
  CREATE_BUCKET: 'CREATE_BUCKETS',

  // LOGGING ACTIONS
  FETCH_LOG_HISTORY: 'FETCH_LOG_HISTORY',
  SET_LOG_HISTORY: 'SET_LOG_HISTORY',
}
